/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessEpubRouteImport } from './routes/api/process-epub'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiDetectLanguageRouteImport } from './routes/api/detect-language'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessEpubRoute = ApiProcessEpubRouteImport.update({
  id: '/api/process-epub',
  path: '/api/process-epub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDetectLanguageRoute = ApiDetectLanguageRouteImport.update({
  id: '/api/detect-language',
  path: '/api/detect-language',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/detect-language': typeof ApiDetectLanguageRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/process-epub': typeof ApiProcessEpubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/detect-language': typeof ApiDetectLanguageRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/process-epub': typeof ApiProcessEpubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/detect-language': typeof ApiDetectLanguageRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/process-epub': typeof ApiProcessEpubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/detect-language' | '/api/logs' | '/api/process-epub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/detect-language' | '/api/logs' | '/api/process-epub'
  id:
    | '__root__'
    | '/'
    | '/api/detect-language'
    | '/api/logs'
    | '/api/process-epub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDetectLanguageRoute: typeof ApiDetectLanguageRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiProcessEpubRoute: typeof ApiProcessEpubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-epub': {
      id: '/api/process-epub'
      path: '/api/process-epub'
      fullPath: '/api/process-epub'
      preLoaderRoute: typeof ApiProcessEpubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/detect-language': {
      id: '/api/detect-language'
      path: '/api/detect-language'
      fullPath: '/api/detect-language'
      preLoaderRoute: typeof ApiDetectLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDetectLanguageRoute: ApiDetectLanguageRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiProcessEpubRoute: ApiProcessEpubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
